version: "3.7"

services:
    # image project
    app:
        build:
            args:
                user: jandrei
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: forest-ai
        container_name: forest-ai-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - forest-ai

    # nginx
    nginx:
        image: nginx:1.17-alpine
        container_name: forest-ai-nginx
        restart: unless-stopped
        ports:
            - "8989:80"
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - forest-ai

    # db mysql
    db:
        image: mysql:8.0.32
        container_name: forest-ai-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        ports:
            - "3388:3306"
        networks:
            - forest-ai

networks:
    forest-ai:
        driver: bridge
